export const object = [
  {
    id: 1,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    imgText: "50% off upto ₹100",
    name: "pizza hut",
    rating: 4.9,
    time: "30-35",
    restoName: "Pizzas",
    area: "balaji nagar",
  },
  {
    id: 2,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b4817ea5bb972089f419c6f14e5a0bdd",
    imgText: "Item at ₹179",
    name: "Chinese wok",
    rating: 4.3,
    time: "40-45",
    restoName: "Chinese, Tibetan, Dessert",
    area: "eternity mall",
  },
  {
    id: 3,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ubypvyevkrogfvj1ygio",
    imgText: "50% off upto ₹100",
    name: "UBQ by Barbeque nation",
    rating: 4.1,
    time: "30-40",
    restoName: "North  indian, barbecur=e, biryani",
    area: "sitabuldi",
  },
  {
    id: 4,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xxh8c7ggvlhlzlx3oyv4",
    imgText: "50% off upto ₹100",
    name: " Barbeque nation",
    rating: 4.2,
    time: "30-40",
    restoName: "North  indian, barbecur=e, biryani",
    area: "sitabuldi",
  },
  {
    id: 5,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f1aa621021a2826088089b89842d4e7c",
    imgText: "Item at ₹149",
    name: `wendy's burger`,
    rating: 4.5,
    time: "20-25",
    restoName: "Burger, american, fast food",
    area: "sadar",
  },
  {
    id: 6,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/s6lf5mdzkldlxsba3rin",
    imgText: "Item at ₹159",
    name: "upwas specials by lunchbox",
    rating: 4.5,
    time: "30-35",
    restoName: "biryani, north indian, desserts",
    area: "trimurti nagar",
  },
  {
    id: 7,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/owmnx4cmhygad1dtxxzw",
    imgText: "50% off upto ₹100",
    name: "kwality walls frozen dessert",
    rating: 4.7,
    time: "15-20",
    restoName: "desserts, ice cream",
    area: "manis nagar",
  },
  {
    id: 8,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d3e1d49bbf3bcd46b86d24c7e03a290f",
    imgText: "₹125 off above ₹249",
    name: "AL zam zam",
    rating: 4.3,
    time: "10-20",
    restoName: "biryani, north indian, mughalai",
    area: "manish nagar",
  },
  {
    id: 9,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/6e04be27387483a7c00444f8e8241108",
    imgText: "50% off ₹100",
    name: "the good bowl",
    rating: 4.3,
    time: "10-20",
    restoName: "biryani, north indian, mughalai",
    area: "manish nagar",
  },
  {
    id: 10,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/y2qnmifzwza6zwxclgky",
    imgText: "Item at ₹159",
    name: "lunchBox- meals and thalis",
    rating: 4.3,
    time: "30-35",
    restoName: "biryani, north indian, punjabi, dessert",
    area: "trimurti nagar",
  },
  {
    id: 11,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/5/f93e4b53-f6f7-4b0f-a58b-2ac21009448c_53415.jpg",
    imgText: "Item at ₹129",
    name: "faasos - wraps, rolls",
    rating: 4.3,
    time: "40-45",
    restoName: "kebabs, fast food, snack",
    area: "trimurti nagar",
  },
];
